### ISSUE TITLE
Exception: 96% of trees are multiprimary (48149 of 50000), so not enough to report good posterior.

### ISSUE THREAD

**Issue by junsung1** [morrislab/phylowgs#107]
Hi, I recently started to use phylowgs but come across with following error when running with my samples. (c.f. running with example data had no issues, I double checked ssm files)

[2019-03-01 17:03:32] Not excluding any chains
[2019-03-01 17:03:18] Chain merging complete.
[2019-03-01 17:03:18] You may remove the following unneeded intermediate files: /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_0/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_1/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_2/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_3/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_4/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_5/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_6/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_7/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_8/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_9/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_10/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_11/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_12/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_13/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_14/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_15/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_16/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_17/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_18/trees.zip /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/chain_19/trees.zip
[2019-03-01 17:03:18] To write JSON results, please run `/home/users/whiungter/anaconda3/bin/python2 /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/write_results.py run_name /home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/chains/trees.zip run_name.summ.json.gz run_name.muts.json.gz run_name.mutass.zip`
write result
Traceback (most recent call last):
  File "/home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/write_results.py", line 57, in <module>
    main()
  File "/home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/write_results.py", line 49, in main
    munger.remove_multiprimary_trees(args.max_multiprimary)
  File "/home/users/whiungter/Projects/03_Clonal_Hematopoiesis/phylowgs/pwgsresults/result_munger.py", line 96, in remove_multiprimary_trees
    len(self._tree_summaries)
Exception: 96% of trees are multiprimary (48149 of 50000), so not enough to report good posterior.

Although I followed a solution from similar thread, increasing --num-chains 4 ->5 (even tried upto 20), I get the same error message. 

Is there any chance, that I can manually turn it off from 'write_results.py' and force to generate output from regarding trees.zip?

many thanks,

**Comment by aleighgreen** [comment]
--allow-polyclonal --include-polyclonal

Are the flags you want to look at

**Comment by mgfield** [comment]
I am having the same issue. How and where do I add those flags? I do not see anywhere that recognizes those.

**Comment by pawelqs** [comment]
Me too. Is it now called "--include-multiprimary"?

**Comment by adhisadi** [comment]
adding --include-multiprimary --max-multiprimary 1 when running write_results.py worked for me.
