### ISSUE TITLE
RuntimeWarning using multievolve.py

### ISSUE THREAD

**Issue by gengyuncong** [morrislab/phylowgs#110]
Hi,
When I run multievolve.py, I encountered the following problem after all MCMCs are done: 

```
multievolve.py:235: RuntimeWarning: invalid value encountered in less
  assert np.all(logSumLHs < 0)
Traceback (most recent call last):
  File "multievolve.py", line 323, in <module>
    main()
  File "multievolve.py", line 319, in main
    included_chains, excluded_chains = determine_chains_to_merge(chain_dirs, args['chain_inclusion_factor'])
  File "multievolve.py", line 235, in determine_chains_to_merge
    assert np.all(logSumLHs < 0)
AssertionError
```

**Comment by gengyuncong** [comment]
I found that the LLH are all "nan" in the chain_*/mcmc_samples.txt. What does that suggest?
