### ISSUE TITLE
multievolve.py: ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by ZiaoLIN** [morrislab/phylowgs#111]
Hi,

This is my first time to use phylowgs and it is possible that I messed up with something. However, the problem is that after following README to git clone the package and compile using the following command:

g++ -o mh.o -O3 mh.cpp  util.cpp `gsl-config --cflags --libs`

I tried to run the following command on the example inputs ssms.txt and cnvs.txt:

python2.7 multievolve.py --num-chains 4 --ssms ssm_data.txt --cnvs cnv_data.txt

Then, the following error shows up:

Traceback (most recent call last):
  File "multievolve.py", line 323, in <module>
    main()
  File "multievolve.py", line 319, in main
    included_chains, excluded_chains = determine_chains_to_merge(chain_dirs, args['chain_inclusion_factor'])
  File "multievolve.py", line 229, in determine_chains_to_merge
    logSumLHs.append(scipy.misc.logsumexp(logLHs))
  File "//anaconda/lib/python2.7/site-packages/numpy/lib/utils.py", line 100, in newfunc
    return func(*args, **kwds)
  File "//anaconda/lib/python2.7/site-packages/scipy/special/_logsumexp.py", line 101, in logsumexp
    a_max = np.amax(a, axis=axis, keepdims=True)
  File "//anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2263, in amax
    out=out, keepdims=keepdims)
  File "//anaconda/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

Any ideas will be appreciated! Thanks so much in advance!

Best,
Ziao

**Comment by vivekruhela** [comment]
@ZiaoLIN :+1: 
Hi,

I am getting the same errror. Have you got any solution.

**Comment by nodanny** [comment]
I met the same error with the example data! Meanwhile, there is an error stating that "/urpath/miniconda2/envs/bioinfo/share/phylowgs/mh.o: error while loading shared libraries: libcblas.so.3: cannot open shared object file: No such file or directory". 
I ran the command below and solved the error.
```
cd /urpath/miniconda2/envs/bioinfo/lib
ln -s libcblas.so libcblas.so.3
```

**Comment by karini925** [comment]
After I renamed the id column to S0 to Sn.... and made sure my SSM file was tab-delimited, the error went away and it ran as expected.

**Comment by aleighbrown** [comment]
We got this error when we forgot to compile the C++ code as an fyi.

**Comment by adhisadi** [comment]
Has anyone come up with any other solution. I have compiled the C++ code, my files are tab-delimited and id columns are named s0 to sn. I still get this error with my data (single sample) and with the example data.
