### ISSUE TITLE
Issue with write results

### ISSUE THREAD

**Issue by sahilseth** [morrislab/phylowgs#118]
multievolve completed successfully with the following message:

```
[2019-11-12 07:45:12] You may remove the following unneeded intermediate files: phylowgs/chain_2/trees.zip phylowgs/chain_3/trees.zip
[2019-11-12 07:45:12] To write JSON results, please run `python write_results.py run_name trees.zip run_name.summ.json.gz run_name.muts.json.gz run_name.mutass.zip`
```

However, when running this command I get the following error:

```
python write_results.py run_name trees.zip run_name.summ.json.gz run_name.muts.json.gz run_name.mutass.zip

starting ResultGenerator
reading file:  trees.zip
Traceback (most recent call last):
  File "write_results.py", line 60, in <module>
    main()
  File "write_results.py", line 45, in main
    summaries, mutlist, mutass, params = ResultGenerator().generate(args.tree_file, args.include_ssm_names)
  File "pwgsresults/result_generator.py", line 14, in generate
    first_tree = next(reader.load_trees())
StopIteration
```
I tried stepping through the code, but can't pinpoint the issue.

- the trees.zip has 5000 tree files along with:
  - params.json
  - cnv_logical_physical_mapping.json

Thanks for the help!

**Comment by sahilseth** [comment]
Wanted to check if someone else has encountered this issue
