### ISSUE TITLE
cnvint Branch Error

### ISSUE THREAD

**Issue by ShadrielleE** [morrislab/phylowgs#35]
Running into some issues when running the evolve.py script in the cnvint branch:

> python $PHYLOWGSROOT/bin/evolve.py ssm_data.txt cnv_data.txt

[2016-06-09 13:58:37.704657] Starting MCMC run...
[2016-06-09 13:58:37.710542] -1000
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/oicr/local/sw/Python-2.7.9/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/oicr/local/sw/Python-2.7.9/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/oicr/local/boutroslab/sw/phylowgs/1.1/bin/evolve.py", line 322, in run
    tmp_dir=args.tmp_dir
  File "/oicr/local/boutroslab/sw/phylowgs/1.1/bin/evolve.py", line 108, in start_new_run
    do_mcmc(state_manager, backup_manager, safe_to_exit, run_succeeded, config, state, tree_writer, codes, n_ssms, n_cnvs, NTPS, tmp_dir)
  File "/oicr/local/boutroslab/sw/phylowgs/1.1/bin/evolve.py", line 180, in do_mcmc
    config['tmp_dir']
  File "/oicr/x86_64/boutroslab/sw/phylowgs/1.1/bin/params.py", line 61, in metropolis
    sp.check_call(['%s/mh.o' % script_dir, MH_ITR, MH_STD, N_SSM_DATA, N_CNV_DATA, NNODES, TREE_HEIGHT, FNAME_SSM_DATA, FNAME_CNV_DATA, FNAME_C_TREE, FNAME_C_DATA_STATES, FNAME_C_PARAMS,FNAME_C_MH_ARATIO, NTPS])
  File "/oicr/local/sw/Python-2.7.9/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/oicr/local/sw/Python-2.7.9/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/oicr/local/sw/Python-2.7.9/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/oicr/local/sw/Python-2.7.9/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[2016-06-09 13:58:41.027338] Run failed.

When I run it the same way using the master branch, it works fine. Anything I missed?

Thanks

**Comment by ShadrielleE** [comment]
Nevermind -- it was an installation issue
