### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by kndeajs** [morrislab/phylowgs#91]
Hi, I am trying to use Phylowgs without cnv files. My codes are as follows.

##parse
nohup /data1/software/phloWGS/phylowgs/parser/create_phylowgs_inputs.py \
--vcf-type P9T1=strelka \
--vcf-type P9T2=strelka --vcf-type P9T3=strelka \
--output-variants P9_ssm_data.txt \
--regions=all \
P9T1=$output/P9T1/results/variants/somatic.snvs.vcf \
P9T2=$output/P9T2/results/variants/somatic.snvs.vcf \
P9T3=$output/P9T3/results/variants/somatic.snvs.vcf > parse.log 2>&1 &

##run
nohup python2 /data1/software/phloWGS/phylowgs/multievolve.py \
--ssms P9_ssm_data.txt --cnvs cnv_data.txt> phyloWGS.log 2>&1 &

No error in parse,but multievolve.py can not work. Then I check the log file, it says
...
[2018-08-28 17:08:17] chain=2 Exception in thread Thread-1:
[2018-08-28 17:08:17] chain=2 Traceback (most recent call last):
[2018-08-28 17:08:17] chain=2 File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
[2018-08-28 17:08:17] chain=2 self.run()
[2018-08-28 17:08:17] chain=2 File "/usr/lib64/python2.7/threading.py", line 765, in run
[2018-08-28 17:08:17] chain=2 self.__target(*self.__args, **self.__kwargs)
[2018-08-28 17:08:17] chain=2 File "/data1/software/phloWGS/phylowgs/evolve.py", line 391, in run
[2018-08-28 17:08:17] chain=2 tmp_dir=paths['tmp_dir']
[2018-08-28 17:08:17] chain=2 File "/data1/software/phloWGS/phylowgs/evolve.py", line 122, in start_new_run
[2018-08-28 17:08:17] chain=2 do_mcmc(state_manager, backup_manager, safe_to_exit, run_succeeded, config, state, tree_writer, codes, n_ssms, n_cnvs, NTPS, tmp_dir)
[2018-08-28 17:08:17] chain=2 File "/data1/software/phloWGS/phylowgs/evolve.py", line 199, in do_mcmc
[2018-08-28 17:08:17] chain=2 config['tmp_dir']
[2018-08-28 17:08:17] chain=2 File "/data1/software/phloWGS/phylowgs/params.py", line 61, in metropolis
[2018-08-28 17:08:17] chain=2 sp.check_call(['%s/mh.o' % script_dir, MH_ITR, MH_STD, N_SSM_DATA, N_CNV_DATA, NNODES, TREE_HEIGHT, FNAME_SSM_DATA, FNAME_CNV_DATA, FNAME_C_TREE, FNAME_C_DATA_STATES, FNAME_C_PARAMS,FNAME_C_MH_ARATIO, NTPS])
[2018-08-28 17:08:17] chain=2 File "/usr/lib64/python2.7/subprocess.py", line 537, in check_call
[2018-08-28 17:08:17] chain=2 retcode = call(*popenargs, **kwargs)
[2018-08-28 17:08:17] chain=2 File "/usr/lib64/python2.7/subprocess.py", line 524, in call
[2018-08-28 17:08:17] chain=2 return Popen(*popenargs, **kwargs).wait()
[2018-08-28 17:08:17] chain=2 File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
[2018-08-28 17:08:17] chain=2 errread, errwrite)
[2018-08-28 17:08:17] chain=2 File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
[2018-08-28 17:08:17] chain=2 raise child_exception
[2018-08-28 17:08:17] chain=2 OSError: [Errno 2] No such file or directory 
...

I wondered what's wrong with my code. 
Thanks for your time.

**Comment by codechenx** [comment]
same error

**Comment by AmitDeshwar** [comment]
Did you compile the C++ code required?
i.e. run `g++ -o mh.o -O3 mh.cpp  util.cpp `gsl-config --cflags --libs`` ?

**Comment by kndeajs** [comment]
@

> Did you compile the C++ code required?
> i.e. run `` g++ -o mh.o -O3 mh.cpp util.cpp `gsl-config --cflags --libs` `` ?
> 
> Did the parser generate a cnv_data.txt file?

**Comment by codechenx** [comment]
I install phylowgs through conda. using my data or data from test(https://github.com/morrislab/phylowgs/tree/master/parser/test/outputs/singlesamp_cnv),I got same error

**Comment by kndeajs** [comment]
> Did you compile the C++ code required?
> i.e. run `` g++ -o mh.o -O3 mh.cpp util.cpp `gsl-config --cflags --libs` `` ?
> 
> Did the parser generate a cnv_data.txt file?

Yes, the parser has generated an empty cnv_data.txt file. Instead, I run Phylowgs with cnv files, it run well

**Comment by AmitDeshwar** [comment]
@codechenx  I'm not sure if the conda package automatically builds the C++ code required.
Can you try cloning the repo and following the instructions in the readme?

**Comment by codechenx** [comment]
@AmitDeshwar Thank you for kind reply， I'll try to install PhyloWGS manual.
