### ISSUE TITLE
Exception: 97% of trees are polyclonal , so not enough to report good posterior.

### ISSUE THREAD

**Issue by kndeajs** [morrislab/phylowgs#95]
Hi，
I   am trying to get the JSON results, and got an error as follows:

Traceback (most recent call last):
  File "/data1/software/phloWGS/phylowgs/write_results.py", line 41, in <module>
    main()
  File "/data1/software/phloWGS/phylowgs/write_results.py", line 33, in main
    munger.remove_polyclonal_trees()
  File "/data1/software/phloWGS/phylowgs/pwgsresults/result_munger.py", line 96, in remove_polyclonal_trees
    len(self._tree_summaries)
Exception: 97% of trees are polyclonal (4896 of 5000), so not enough to report good posterior.

What does it mean? How can I deal with it?

**Comment by codechenx** [comment]
same question

**Comment by codechenx** [comment]
same question

**Comment by kndeajs** [comment]
> I had got the same error. and I found my sample's ssm_data.txt is wrong, the value of column 'a' and column 'b' was same for the reason of the wrong input parse. Hope this will help you.

Thanks for your advice. I will try it

**Comment by quaidmorris** [comment]
We put this in to address concerns that PhyloWGS was overcalling polytumours (i.e. tumour samples containing DNA from multiple, separate primaries). I suggest trying PhyloWGS in multichain mode with at least five chains. If you still get this error, we will add a command line argument to turn this quality control off.

**Comment by aleighgreen** [comment]
Have been running with 4, will bump up to 5 now.

That being said, what if the tumor really is poly? Wouldn't we want to be
able to explore that as well?

**Comment by quaidmorris** [comment]
Yes, let's why we're going to permit you to turn off this check on the command line. If you keep getting a polytumour reconstruction, then that sounds like evidence that there is a poly reconstruction consistent with your data.

**Comment by aleighgreen** [comment]
Great, in this particular case increasing up to 5 solved this error. Thanks! Would you say in general that increasing the number of chains would help with this type of error if indeed the tumors are not polyclonal? Is there a minimum number of chains you would recommend running? 



It might be helpful anyway to release something that allows you to turn it off on the cmd line. We've got some weird samples, it would not surprise me if some of them were truly polyclonal tumors.

**Comment by mgfield** [comment]
Having same issue even with running 40 chains.  How do I turn this off?

**Comment by RupalHatkar** [comment]
I changed the chain number but it didn't help. I am not getting any error message and exit status=o
Any suggestions?
